name: Create Main Sync Pull Request
on:
  push:
    branches:
      - "release-*"

jobs:
  syncMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch and reset branch
        run: |
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}

      - name: Get Last Commit Message
        id: last_commit
        run: |
          LAST_COMMIT_MSG=$(git log origin/${{ github.ref_name }} -1 --pretty=%B)
          echo "commit_message=$LAST_COMMIT_MSG" >> $GITHUB_ENV

      - name: Extract PR Number from Commit Message
        id: pr_number
        run: |
          PR_NUMBER=$(echo "${{ env.commit_message }}" | grep -oE "\(#([0-9]+)\)" | sed -E 's/\(#([0-9]+)\)/\1/')
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR number found, setting to 'N/A'"
            PR_NUMBER="N/A"
          fi
          echo "pr_url=https://github.com/${{ github.repository }}/pull/$PR_NUMBER" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: main-${{ github.ref_name }}
          title: "${{ env.commit_message }} (to main)"
          body: "Automated changes by [this-pull-request](${{ env.pr_url }})"